---
# tasks file for docker-registry
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: youssefhaffar
    password: pkhklhlh21!?
    email: mohamedyoussef.haffar@esprit.tn
- name: Push to docker hub
  docker_image:
    name: devops
    repository: youssefhaffar/liv
    tag: latest
    source: local
    push: yes
